### ISSUE TITLE
enable multiple property files

### ISSUE THREAD

**Issue by bodsch** [bodsch/ansible-container#20]
At present, exactly one *properties* file can be created:

```
container:
  - name: hello-world
    hostname: hello-world
    image: hello-world:latest
    properties:
      #
      publisher.maxRecursionDepth: 200
      # user and password for login to the staging serve
      replicator.user: 'replicator'
      replicator.password: 'replicator'
      # replicator.domain: ''
      replicator.tmp_dir: 'var/tmp'
```

Sometimes, however, it makes sense to include a set of *properties* files for the container - depending on the application.

Therefore, the role should be extended to support multiple files per container.

Perhaps a new variable can be used for this purpose:

```
container:
  - name: hello-world
    hostname: hello-world
    image: hello-world:latest
    property_file:
      - name: publisher.properties
        properties:
          #
          publisher.maxRecursionDepth: 200
          # user and password for login to the staging serve
          replicator.user: 'replicator'
          replicator.password: 'replicator'
          # replicator.domain: ''
          replicator.tmp_dir: 'var/tmp'
      - name: database.properties
        properties:
          #
          sql.storage: ...
          
```
