### ISSUE TITLE
support multiple container registries

### ISSUE THREAD

**Issue by bodsch** [bodsch/ansible-container#25]
Currently, the login is only supported in one registry.
```
container_registry:
  host: ''
  username: ''
  password: ''
```

However, containers from different registries may be required.
In this case, the configuration should be extended accordingly.

Proposal:
```
container_registry:
  - registry: ''
    username: ''
    password: ''
```
Please make the extension of the configuration downward compatible!
